# Generated by Django 5.0.2 on 2024-03-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.TextField(max_length=50)),
                ('body_part', models.TextField(max_length=5)),
                ('description', models.TextField(default='basic exercise description', max_length=300)),
                ('type', models.CharField(choices=[('BB', 'Barbell'), ('CAB', 'Cable'), ('DB', 'Dumbbell'), ('BW', 'Body Weight')], default='BB', max_length=5)),
            ],
            options={
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setNumber', models.IntegerField()),
                ('setReps', models.IntegerField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('setExercise', models.ManyToManyField(related_name='sets', to='gym.exercise')),
            ],
            options={
                'db_table': 'sets',
            },
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.TextField(max_length=30)),
                ('exercise', models.ManyToManyField(related_name='workouts', to='gym.exercise')),
            ],
        ),
    ]
