# Generated by Django 5.0.2 on 2024-04-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='workout_name',
            field=models.TextField(max_length=30, unique=True),
        ),
    ]
